site_name: retrio
nav:
  - Home: index.md
  - Usage: usage.md
  - Examples: examples.md
  - Architecture: architecture.md
  - Observability: observability.md
  - Best Practices: best_practices.md
  - Migration: migration.md
  - Benchmarks: benchmarks.md

theme:
  name: material

extra:
  repository_url: https://github.com/RamanaMenda/retrio
